spring:
  datasource:
    url: jdbc:h2:file:/Users/a18188916/Documents/study/prediction_bot/src/main/resources/data/data
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true